# Generated by Django 2.2 on 2019-06-20 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(max_length=50)),
                ('regimen', models.SmallIntegerField(choices=[(1, 'Subsidiado'), (2, 'Contributivo')])),
            ],
            options={
                'db_table': 'eps',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('genero', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculacion', models.SmallIntegerField(choices=[(1, 'Cotizante'), (2, 'Beneficiario')])),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citas.Eps')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Citamedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocita', models.CharField(max_length=50)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Aprobada'), (2, 'Rechazada'), (3, 'Ejecutada')])),
                ('fecha', models.DateTimeField()),
                ('costo', models.FloatField()),
                ('pago', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('descripcion', models.CharField(max_length=250)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citas.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citas.Paciente')),
            ],
            options={
                'db_table': 'citamedica',
            },
        ),
    ]
